package com.ua_guys.service;

import com.ua_guys.service.bosch.ParkingPlaceParameters;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.Collections;

@Service
@RequiredArgsConstructor
@Slf4j
public class BoschApiService {

  private static final String BOSCH_API_URL =
      "https://things.eu-1.bosch-iot-suite.com/api/2/search/things?namespaces=io.bosch.bcx2020";
  private static final String API_KEY_VALUE =
      "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJwRlhzTXhHaG5YSmd6ZzlhTzl4WVVUWWVnQ1A0WHNudUdoUUVlUWFBUXJJIn0.eyJqdGkiOiJkNDcxNGQ4MS1kYmYwLTRlZmEtYjQwMS0xZGFlNTg2YjdiNjkiLCJleHAiOjE1ODE4MzEzNjcsIm5iZiI6MCwiaWF0IjoxNTgxODI3NzY3LCJpc3MiOiJodHRwczovL2FjY2Vzcy5ib3NjaC1pb3Qtc3VpdGUuY29tL2F1dGgvcmVhbG1zL2lvdC1zdWl0ZSIsImF1ZCI6WyJzZXJ2aWNlOmlvdC10aGluZ3MtZXUtMTphODYwZDRjMS0yMzUxLTQ5NjUtODJkMC1lYmMzNzdhYTE5YWFfdGhpbmdzIiwic2VydmljZTppb3QtaHViLXByb2Q6dGE4NjBkNGMxMjM1MTQ5NjU4MmQwZWJjMzc3YWExOWFhX2h1YiIsImFjY291bnQiXSwic3ViIjoiY2M5YzBlN2UtNWNjZS00MzVkLWFkMjQtOWY0MDlkZGYyMTgzIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiOTY5ZThjYzctMjc3ZS00MWEyLWE2YmItN2E4MTVkY2UzMTY4IiwiYXV0aF90aW1lIjowLCJzZXNzaW9uX3N0YXRlIjoiOTExMjFlMGYtYTc3OS00MDA1LTg3MDUtYmI2MjM0ODNiZGVhIiwiYWNyIjoiMSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsic2VydmljZTppb3QtdGhpbmdzLWV1LTE6YTg2MGQ0YzEtMjM1MS00OTY1LTgyZDAtZWJjMzc3YWExOWFhX3RoaW5ncyI6eyJyb2xlcyI6WyJmdWxsLWFjY2VzcyJdfSwic2VydmljZTppb3QtaHViLXByb2Q6dGE4NjBkNGMxMjM1MTQ5NjU4MmQwZWJjMzc3YWExOWFhX2h1YiI6eyJyb2xlcyI6WyJmdWxsLWFjY2VzcyJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiY2xpZW50SG9zdCI6IjMuMTIzLjg4LjE5OCIsImNsaWVudElkIjoiOTY5ZThjYzctMjc3ZS00MWEyLWE2YmItN2E4MTVkY2UzMTY4IiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJzZXJ2aWNlLWFjY291bnQtOTY5ZThjYzctMjc3ZS00MWEyLWE2YmItN2E4MTVkY2UzMTY4IiwiY2xpZW50QWRkcmVzcyI6IjMuMTIzLjg4LjE5OCIsImVtYWlsIjoic2VydmljZS1hY2NvdW50LTk2OWU4Y2M3LTI3N2UtNDFhMi1hNmJiLTdhODE1ZGNlMzE2OEBwbGFjZWhvbGRlci5vcmcifQ.k2kMAEYaO9Kb6WDNjn6TPBXMb4ETfflykpLLCrremxxsPcRFSkN_qxK9uKIQEGI1SAdW3FHqqYKVgjUOsJk9yWdmFXR7pXkb-50odPtw6Lwr8pwTexnDKtNHc1s-YazbPEgWdxcrp-jxRN3iMOvuZ2aGwHjW6MkyIxNu0KWcAvC_aMWxgXMyuu4Itb6kaAKHYkO6DMlJqBuB0R2yqW0lWTLJ8Pbczg7axNHgP7lZw-w0vq7FY1HMRhCDGU8DtABN0YOsmfnmmpvNra6qRMxRmgTUmYe-hihmy7QMtid3bt4IZSGU4OzAUAvtn1NBmr0J4KElOrxZZL-aeCW0WP7mjw";
  public static final String API_KEY = "Authorization";

  private final RestTemplate restTemplate;

  public ParkingPlaceParameters getDataFromParkingSensors() {
    String url = BOSCH_API_URL;

    HttpHeaders headers = getHttpHeaders();

    HttpEntity request = new HttpEntity<>(headers);

    ResponseEntity<ParkingPlaceParameters> responseEntity =
        restTemplate.exchange(url, HttpMethod.GET, request, ParkingPlaceParameters.class);
    return responseEntity.getBody();
  }

  private HttpHeaders getHttpHeaders() {
    HttpHeaders headers = new HttpHeaders();
    headers.add(API_KEY, API_KEY_VALUE);
    headers.setAccept(Collections.singletonList(MediaType.APPLICATION_JSON));
    headers.setContentType(MediaType.APPLICATION_JSON);
    return headers;
  }
}
